version: '3.8'

services:
  frontend-master:
    build: ./frontend-master/Angulardockerfilecreate-main
    ports:
      - "8080:80"
    depends_on:
      - backend-master

  backend-master:
    build: ./backend-master/demoJavaProject
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=host.docker.internal  # Connect to host's MySQL
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=timp

  frontend-dev:
    build: ./frontend-dev/Angulardockerfilecreate-main
    ports:
      - "4200:4200"
    depends_on:
      - backend-dev
    volumes:
      - ./frontend-dev/Angulardockerfilecreate-main:/app
    command: npm start

  backend-dev:
    build: ./backend-dev/demoJavaProject
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=host.docker.internal  # Connect to host's MySQL
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=timp
    volumes:
      - ./backend-dev/demoJavaProject:/app
