version: '3.8'

services:
  frontend-master:
    build: ./frontend-master/Angulardockerfilecreate-main
    ports:
      - "8080:80"
    depends_on:
      - backend-master

  backend-master:
    build: ./backend-master/demoJavaProject
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=mydb
    depends_on:
      - db

  frontend-dev:
    build: ./frontend-dev/Angulardockerfilecreate-main
    ports:
      - "4200:4200"
    depends_on:
      - backend-dev
    volumes:
      - ./frontend-dev/Angulardockerfilecreate-main:/app
    command: npm start

  backend-dev:
    build: ./backend-dev/demoJavaProject
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=mydb
    depends_on:
      - db
    volumes:
      - ./backend-dev/demoJavaProject:/app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql   # Bind local DB files
